steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - southamerica-east1-docker.pkg.dev/biconect/app-repo/biconnect-frontend:latest
    - --build-arg
    - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}
    - --build-arg
    - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}
    - .
images:
- southamerica-east1-docker.pkg.dev/biconect/app-repo/biconnect-frontend:latest
